version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pyohio22demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r44khjvd6yo5"
s3_prefix = "pyohio22demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
